module SkelGrammar where

-- Haskell module generated by the BNF converter

import AbsGrammar
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  Program stmts -> failure x
transBlock :: Block -> Result
transBlock x = case x of
  Block stmts -> failure x
transStmt :: Stmt -> Result
transStmt x = case x of
  BStmt block -> failure x
  Decl type_ item -> failure x
  Ass ident expr -> failure x
  Ret expr -> failure x
  VRet -> failure x
  Cond expr block -> failure x
  CondElse expr block1 block2 -> failure x
  While expr stmt -> failure x
  For ident expr1 expr2 stmt -> failure x
  ForIn ident expr stmt -> failure x
  Print expr -> failure x
  SFormat string exprs -> failure x
  SExp expr -> failure x
  FnDef ident args type_ block -> failure x
  ListPush ident expr -> failure x
transItem :: Item -> Result
transItem x = case x of
  NoInit ident -> failure x
  Init ident expr -> failure x
transArg :: Arg -> Result
transArg x = case x of
  Arg type_ ident -> failure x
  RefArg type_ ident -> failure x
transType :: Type -> Result
transType x = case x of
  TInt -> failure x
  TBool -> failure x
  TString -> failure x
  Void -> failure x
  TList type_ -> failure x
  AnonFun type_ typeorrefs -> failure x
transTypeOrRef :: TypeOrRef -> Result
transTypeOrRef x = case x of
  TypeOrRefType type_ -> failure x
  TypeOrRefRef type_ -> failure x
transExpr :: Expr -> Result
transExpr x = case x of
  ListLength expr -> failure x
  ListAt expr1 expr2 -> failure x
  ELambda idents args type_ block -> failure x
  ELitInt integer -> failure x
  EVar ident -> failure x
  ELitTrue -> failure x
  ELitFalse -> failure x
  EEmptyList type_ -> failure x
  EString string -> failure x
  EApp expr exprorrefs -> failure x
  Neg expr -> failure x
  Not expr -> failure x
  EMul expr1 mulop expr2 -> failure x
  EAdd expr1 addop expr2 -> failure x
  ERel expr1 relop expr2 -> failure x
  EAnd expr1 expr2 -> failure x
  EOr expr1 expr2 -> failure x
transExprOrRef :: ExprOrRef -> Result
transExprOrRef x = case x of
  ERExpr expr -> failure x
  ERRef ident -> failure x
transAddOp :: AddOp -> Result
transAddOp x = case x of
  Plus -> failure x
  Minus -> failure x
transMulOp :: MulOp -> Result
transMulOp x = case x of
  Times -> failure x
  Div -> failure x
  Mod -> failure x
transRelOp :: RelOp -> Result
transRelOp x = case x of
  LTH -> failure x
  LE -> failure x
  GTH -> failure x
  GE -> failure x
  EQU -> failure x
  NE -> failure x

